/* ── Adobe Yukon Integration ──────────────────────────────────────────────────
 * Handles:
 *   1. Generating LLM-friendly health check summary documents
 *   2. Uploading those documents to a Yukon collection
 *   3. Streaming Q&A against the collection via SSE
 *
 * Settings (stored via electronAPI.saveSettings):
 *   yukonBaseUrl     — Yukon API base URL (e.g. https://firefly-api.adobe.io)
 *   yukonToken       — Adobe IMS bearer token
 *   yukonCollectionId — Target collection UUID
 * ---------------------------------------------------------------------------- */
const Yukon = (() => {

  // ── Settings cache ────────────────────────────────────────────────────────
  // Populated at app boot (from saved disk settings) and on every settings save,
  // so the chat works immediately without a round-trip to disk each time.
  // Always fetches fresh from the backend so a token rotated on the server is
  // picked up immediately without requiring an app restart.
  async function _getSettings() {
    try {
      if (typeof API !== 'undefined') {
        const res = await API.yukon.config();
        const d   = res.data || res;
        return {
          yukonBaseUrl:        d.yukon_base_url        || '',
          yukonToken:          d.yukon_token            || '',
          yukonCollectionId:   d.yukon_collection_id   || '',
          yukonApiKey:         d.yukon_api_key          || '',
          yukonInferenceMode:  d.yukon_inference_mode   || 'STANDARD',
          yukonResponseFormat: d.yukon_response_format  || 'PARAGRAPH',
          yukonResponseStyle:  d.yukon_response_style   || 'DESCRIPTIVE',
          yukonResponseTone:   d.yukon_response_tone    || 'DIRECT',
        };
      }
    } catch { /* fall through */ }
    return {};
  }

  // configure() is kept for API compatibility but is a no-op now that settings
  // are always fetched live from the backend.
  function configure(_settings) {}

  function _isConfigured(s) {
    return !!(s && s.yukonBaseUrl && s.yukonToken && s.yukonCollectionId);
  }

  // ── HC document generator ────────────────────────────────────────────────
  // Produces a structured markdown document optimised for RAG indexing.
  function generateHCDocument(hc, docs = []) {
    const ownerName = [hc.owner_first_name, hc.owner_last_name].filter(Boolean).join(' ')
                    || hc.owner_email || '—';
    const scoreLabel = hc.avg_score != null
      ? `${hc.avg_score}/100 (${hc.avg_score >= 75 ? 'Good' : hc.avg_score >= 50 ? 'Needs improvement' : 'Poor'})`
      : 'Not yet scored';

    const lines = [
      `# Health Check: ${hc.name}`,
      '',
      `## Summary`,
      `This document is an automated summary of health check "${hc.name}" created for ${hc.customer_name || 'the customer'}.`,
      '',
      `## Metadata`,
      `| Field | Value |`,
      `|-------|-------|`,
      `| Health Check ID | ${hc.id} |`,
      `| Name | ${hc.name} |`,
      `| Customer | ${hc.customer_name || hc.customer_id || '—'} |`,
      `| Status | ${hc.status || '—'} |`,
      `| DR Number | ${hc.dr_number || '—'} |`,
      `| Owner | ${ownerName} |`,
      `| Created | ${hc.created_at || '—'} |`,
      `| Average Score | ${scoreLabel} |`,
      `| Total Documents | ${docs.length || hc.doc_count || 0} |`,
    ];

    if (docs.length) {
      lines.push('');
      lines.push(`## Documents Analysed (${docs.length})`);
      docs.forEach((d, i) => {
        const docName  = d.file_name || d.name || `Document ${i + 1}`;
        const docScore = d.score != null ? d.score : (d.avg_score != null ? d.avg_score : null);
        lines.push('');
        lines.push(`### ${docName}`);
        lines.push(`| Field | Value |`);
        lines.push(`|-------|-------|`);
        lines.push(`| Document ID | ${d.id || '—'} |`);
        lines.push(`| Status | ${d.status || '—'} |`);
        if (docScore != null) lines.push(`| Score | ${docScore}/100 |`);
        if (d.pages)          lines.push(`| Pages | ${d.pages} |`);
        if (d.created_at)     lines.push(`| Uploaded | ${d.created_at} |`);

        if (d.summary) {
          lines.push('');
          lines.push(`**Summary:** ${d.summary}`);
        }
        if (d.findings && d.findings.length) {
          lines.push('');
          lines.push('**Findings:**');
          d.findings.forEach(f => {
            lines.push(`- **${f.category || f.name}**: ${f.description || f.detail || ''} (Score: ${f.score ?? '—'})`);
          });
        }
        if (d.categories && d.categories.length) {
          lines.push('');
          lines.push('**Category Scores:**');
          d.categories.forEach(c => {
            lines.push(`- ${c.name}: ${c.score ?? '—'}`);
          });
        }
      });
    }

    lines.push('');
    lines.push('---');
    lines.push(`*Generated by PDF Health Check app on ${new Date().toISOString()}*`);

    return lines.join('\n');
  }

  // ── Upload HC document to a Yukon collection ─────────────────────────────
  // Fire-and-forget: logs warnings but never throws so it can't break HC creation.
  async function uploadHCDocument(hc, docs = []) {
    const s = await _getSettings();
    if (!_isConfigured(s)) return;  // Yukon not configured — silently skip

    const content  = generateHCDocument(hc, docs);
    const safeName = (hc.name || 'healthcheck').replace(/[^a-z0-9]+/gi, '_').toLowerCase().slice(0, 60);
    const filename = `hc_${hc.id}_${safeName}.md`;
    const blob     = new Blob([content], { type: 'text/markdown' });
    const form     = new FormData();
    form.append('documents', blob, filename);

    try {
      const base = s.yukonBaseUrl.replace(/\/$/, '');
      const res  = await fetch(
        `${base}/api/v2/collection/${encodeURIComponent(s.yukonCollectionId)}/upload?option=FILE_NAME`,
        {
          method:  'POST',
          headers: _authHeaders(s.yukonToken, s.yukonApiKey),
          body:    form,
        }
      );
      if (!res.ok) {
        console.warn('[Yukon] Upload failed:', await _responseError(res));
      } else {
        console.log(`[Yukon] Uploaded ${filename} to collection ${s.yukonCollectionId}`);
      }
    } catch (e) {
      console.warn('[Yukon] Upload error:', e.message);
    }
  }

  // ── Build auth headers ────────────────────────────────────────────────────
  // Centralised so all requests pick up x-api-key when the user has set one.
  function _authHeaders(token, apiKey) {
    const h = { 'Authorization': `Bearer ${token.trim()}` };
    if (apiKey && apiKey.trim()) h['x-api-key'] = apiKey.trim();
    return h;
  }

  // ── Friendly error from a non-ok Response ────────────────────────────────
  async function _responseError(res) {
    const body = await res.text().catch(() => '');
    let msg = `HTTP ${res.status}`;
    try {
      const parsed = JSON.parse(body);
      msg = parsed.detail || parsed.message || parsed.error || msg;
    } catch {
      if (body) msg = body.slice(0, 160);
    }
    if (res.status === 401) msg += ' — token may be expired or invalid. Paste a fresh Adobe IMS token and try again.';
    if (res.status === 403) msg += ' — insufficient permissions for this collection.';
    return msg;
  }

  // ── Test connection ──────────────────────────────────────────────────────
  // Returns { ok: true } or { ok: false, error: '...' }
  async function testConnection(baseUrl, token, collectionId, apiKey = '') {
    try {
      const base = baseUrl.replace(/\/$/, '');
      const res  = await fetch(
        `${base}/api/v2/collection/${encodeURIComponent(collectionId)}`,
        { headers: _authHeaders(token, apiKey) }
      );
      if (res.ok) return { ok: true };
      return { ok: false, error: await _responseError(res) };
    } catch (e) {
      return { ok: false, error: e.message };
    }
  }

  // ── Streaming Q&A ────────────────────────────────────────────────────────
  // Async generator — yields { text, event } chunks, then { done: true, sources }
  // Throws on network/auth error.
  async function* streamAnswer(question) {
    const s = await _getSettings();
    if (!_isConfigured(s)) throw new Error('Yukon is not configured. Add your settings in the Settings page.');

    const body = JSON.stringify({
      collections:     [s.yukonCollectionId],
      inputs:          question,
      source_options:  ['COLLECTION'],
      inference_mode:  s.yukonInferenceMode  || 'STANDARD',
      response_format: {
        format:    s.yukonResponseFormat || 'PARAGRAPH',
        style:     s.yukonResponseStyle  || 'DESCRIPTIVE',
        tone:      s.yukonResponseTone   || 'DIRECT',
        reasoning: 'ENABLED',
      },
      response_events: { enabled: true, detail: 'minimal' },
    });

    const base = s.yukonBaseUrl.replace(/\/$/, '');
    const res  = await fetch(`${base}/api/v2/inference/question-answer/stream`, {
      method:  'POST',
      headers: { ..._authHeaders(s.yukonToken, s.yukonApiKey), 'Content-Type': 'application/json' },
      body,
    });

    if (!res.ok) {
      throw new Error(await _responseError(res));
    }

    const reader  = res.body.getReader();
    const decoder = new TextDecoder();
    let   buf     = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });
      const lines = buf.split('\n');
      buf = lines.pop(); // keep partial line

      for (const line of lines) {
        if (!line.startsWith('data:')) continue;
        const raw = line.slice(5).trim();
        if (!raw || raw === '[DONE]') continue;
        try {
          const parsed = JSON.parse(raw);
          const chunk  = Array.isArray(parsed) ? parsed[0] : parsed;
          if (chunk.stream_complete) {
            // The final event may include a last generated_text fragment — yield it
            // before signalling done so the consumer can append the tail text.
            if (chunk.generated_text) {
              yield { text: chunk.generated_text };
            }
            yield { done: true, sources: chunk.source || {} };
            return;
          }
          // Intermediate text delta — yield so the consumer can append it.
          // Guard: skip null/empty fragments that the API emits during progress phases.
          if (chunk.generated_text != null && chunk.generated_text !== '') {
            yield { text: chunk.generated_text, event: chunk.response_event };
          } else if (chunk.response_event) {
            yield { progressEvent: chunk.response_event };
          }
        } catch { /* skip malformed chunks */ }
      }
    }
    // Stream ended without explicit stream_complete
    yield { done: true, sources: {} };
  }

  // ── App guide document ───────────────────────────────────────────────────
  // A static how-to guide uploaded to the Yukon collection so the AI can answer
  // "how do I…" questions about using the PDF Health Check application.
  function generateGuideDocument() {
    return `# PDF Health Check App — User Guide

## Overview
The PDF Health Check (HC) application helps Adobe teams assess the quality, accessibility, and compliance of customer PDF documents. Health checks organise documents into projects, score them automatically using AI, and generate detailed reports.

---

## How to Perform a Health Check

1. **Navigate to Health Checks** — click "Health Checks" in the left sidebar.
2. **Create a new health check** — click the "+ New Health Check" button (top-right). Fill in the name, select a customer, add a DR number (optional), and confirm.
3. **Upload PDFs** — inside the health check, click "Upload PDFs" or drag-and-drop files into the upload area. Multiple PDFs can be uploaded at once.
4. **Wait for scoring** — after upload, documents are processed and scored automatically. The progress indicator shows the current stage (extracting text, scoring categories, generating summary).
5. **Review results** — once complete, each document shows a score out of 100, broken down by category (accessibility, security, structure, metadata, etc.).
6. **View document detail** — click any document row to see the full per-category breakdown, individual findings, and AI-generated summary.
7. **Mark the health check as complete** — use the status dropdown to move the HC from "In Progress" to "Complete" or another relevant status.

---

## How to Upload PDFs

- Open a health check and click **"Upload PDFs"** (blue button, top-right of the documents table).
- Drag and drop PDF files onto the upload dialog, or click to browse.
- Multiple files can be uploaded simultaneously. The progress panel (bottom-right) tracks each file.
- Files that fail to process will show an error status — you can re-upload them individually.
- There is no hard file-size limit, but very large PDFs (>100 pages) may take longer to process.

---

## How to Download PDFs / Reports

- **Individual document PDF** — open a document's detail view and click the download icon next to the filename.
- **Health check report (PDF)** — from a completed health check, click "Export PDF Report" (top-right menu). This generates a formatted summary report for the customer.
- **CSV export** — from the Reports tab, select a health check and choose "Export CSV" to download a spreadsheet of all scores and findings.
- **Customer report** — navigate to a customer and open their report tab for a consolidated view that can also be exported.

---

## How to Manage Customers

- **Add a customer** — go to "Customers" in the sidebar and click "+ New Customer". Enter the company name and any other details.
- **View customer health checks** — click a customer row to open their detail view, showing all associated health checks and their scores over time.
- **Edit customer details** — use the edit icon next to the customer name in the detail view.

---

## How to Use the Reports Tab

The Reports section provides aggregated analytics:
- **Overview** — average scores across all health checks; filterable by date range, customer, or owner.
- **Timeline** — score trends over time. Select a date range using the period selector (1 month, 3 months, 6 months, 1 year, or all time).
- **By Category** — breakdown of scores across the five PDF quality categories.
- **By Customer** — rank customers by their average health check score.

---

## How to Use the AI Assistant (Yukon Chat)

The AI Assistant button (bottom-right of every screen) opens the Yukon chat panel. You can ask it:
- Questions about specific health checks: *"What were the main issues in the ACME Corp health check?"*
- Comparisons: *"Which health checks have the lowest accessibility scores?"*
- Guidance: *"How do I perform a health check?"*, *"How do I download a PDF report?"*
- Summaries: *"Summarise all health checks completed this month."*

**Context awareness** — when you are viewing a specific health check or customer, the AI automatically scopes its answers to that context. The blue banner at the top of the chat panel shows the active context.

**Conversation history** — your chat history is saved automatically. To browse past conversations, open Settings → Adobe Yukon AI → Conversation History. Click any session to restore it.

---

## Scoring Categories

Each PDF is scored in five categories (0–100 each), with an overall average:

| Category | What is measured |
|----------|-----------------|
| **Accessibility** | Tags, reading order, alt text, language declaration |
| **Security** | Password protection, permissions, encryption |
| **Structure** | Bookmarks, headings, table of contents |
| **Metadata** | Title, author, subject, keywords |
| **Compliance** | PDF/A or PDF/UA standard adherence |

Scores ≥ 75 = Good · 50–74 = Needs improvement · < 50 = Poor

---

## How to Use the Report Builder

The **Report Builder** (sidebar → bar-chart icon, or ⌘6) lets you create custom reports from the health-check database — no SQL needed.

### Steps
1. Click **Report Builder** in the left sidebar.
2. Click **+ New Report** (or open an existing saved report from the list).
3. In the left configuration panel, set your options:
   - **Scope** — limit data to your own records, a specific customer, region, vertical, segment, or country.
   - **Date Range** — last 7, 30, 90, 365 days, this year, or all time.
   - **Group By** — choose a dimension (customer, region, vertical, month, creator app, etc.) or leave blank for KPI mode (single summary values).
   - **Metrics** — tick any combination of 25+ metrics. Use the search box to find metrics quickly.
   - **Visualization** — bar, horizontal bar, line, area, pie, donut, or table.
   - **Sort & Limit** — highest or lowest first, capped at a chosen row count.
   - **Filters** — add one or more field-level filters (e.g. "country equals US", "encrypted = No").
4. Click **Run** to see the result in the live preview panel on the right.
5. Give the report a name and click **Save Report** to persist it.

### Sharing and exporting
- **Share to library** — makes the report available to all users under the Shared Library tab.
- **Export PDF** — generates an accessible, tagged PDF via Adobe PDF Services.
- **Export Excel** — downloads the result as an .xlsx spreadsheet.
- **Copy Image** — copies the chart as a PNG to your clipboard.
- **Pin to Dashboard** — adds the report as a live widget on the Dashboard. Widgets refresh automatically each time the dashboard loads.

### Dashboard widgets
- Drag the handle at the bottom of a widget to **resize its height**.
- Click the ⟷ button in the widget header to cycle its **width** (1, 2, or 3 columns).
- Use the ↑ ↓ buttons to **reorder** widgets.
- Click × to **unpin** a widget.
- Click **+ New Report** in the "My Pinned Reports" header to **pin a saved report directly from the dashboard** without entering the builder.

---

## Settings

Access settings from the gear icon (top-right toolbar) or via the keyboard shortcut ⌘,. Tabs include:
- **Profile** — your name and email (used to scope your data).
- **Appearance** — light / dark / auto theme.
- **Language** — UI language (English, Dutch, French, German, Swedish, Spanish, Italian).
- **Backend Connection** — API base URL and credentials for the scoring service.
- **Adobe Yukon AI** — Yukon API URL, bearer token, collection ID, and inference settings.
- **Admin** — admin-only functions.
- **Shortcuts** — keyboard shortcut reference.

---

*This guide is automatically maintained by the PDF Health Check application.*
*Last updated: ${new Date().toISOString().slice(0, 10)}*
`;
  }

  // Uploads the app guide to the configured Yukon collection.
  // Accepts optional explicit credentials (baseUrl, token, collectionId) so callers
  // can pass the current form values without requiring a prior save — the same pattern
  // used by testConnection(). Falls back to stored settings when omitted.
  // Returns { ok: true } or { ok: false, error: string }.
  async function uploadGuideDocument(baseUrl, token, collectionId, apiKey = '') {
    let s;
    if (baseUrl && token && collectionId) {
      s = { yukonBaseUrl: baseUrl, yukonToken: token, yukonCollectionId: collectionId, yukonApiKey: apiKey };
    } else {
      s = await _getSettings();
    }
    if (!_isConfigured(s)) return { ok: false, error: 'Yukon is not configured. Enter the base URL, token, and collection ID first.' };

    const content  = generateGuideDocument();
    const filename = 'hcapp_user_guide.md';
    const blob     = new Blob([content], { type: 'text/markdown' });
    const form     = new FormData();
    form.append('documents', blob, filename);

    try {
      const base = s.yukonBaseUrl.replace(/\/$/, '');
      const res  = await fetch(
        `${base}/api/v2/collection/${encodeURIComponent(s.yukonCollectionId)}/upload?option=FILE_NAME`,
        {
          method:  'POST',
          headers: _authHeaders(s.yukonToken, s.yukonApiKey),
          body:    form,
        }
      );
      if (!res.ok) {
        return { ok: false, error: await _responseError(res) };
      }
      console.log(`[Yukon] Uploaded ${filename} to collection ${s.yukonCollectionId}`);
      return { ok: true };
    } catch (e) {
      return { ok: false, error: e.message };
    }
  }

  return { configure, uploadHCDocument, uploadGuideDocument, streamAnswer, testConnection, generateHCDocument, generateGuideDocument };
})();
